### ISSUE TITLE
The txt files of VisEvent

### ISSUE THREAD

**Issue by Tianlu-Zhang** [Event-AHU/COESOT#1]
Thanks for your work. As mentioned in the paper, 205 training sequences and 171 testing videos in VisEvent dataset are selected to evaluate the tracker’s performance. Could you offer the used video's name? And I also cannot find the raw results and trained models of VisEvent Dataset and FE108 Dataset.

**Comment by Tchuanm** [comment]
Hi, attached are the used videos name txt files. 
[test_list.txt](https://github.com/Event-AHU/COESOT/files/10791343/test_list.txt)
[train_list.txt](https://github.com/Event-AHU/COESOT/files/10791345/train_list.txt)

**Comment by RaymondCover** [comment]
Really thanks for your help😀
