### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by Heyuting-Creator** [Event-AHU/COESOT#10]
Hello, thank you very much for your open source! Can you please tell me that in the processing of COESOT dataset, running _python coesot_choose_videos.py_, there exists too many empty, how do you deal with it?

**Comment by Tchuanm** [comment]
Hi,  Some videos are truly very sparse, especially in some no-motion scenes.  That's the basic features of event camera and we  don't need to deal with it. The event camera mainly contributes to motion scenes.
