### ISSUE TITLE
event_to_voxel_coesot

### ISSUE THREAD

**Issue by Heyuting-Creator** [Event-AHU/COESOT#11]
Hi, in _event_to_voxel_coesot.py_  you set 

_if foldName in ['dvSave-2022_01_26_20_01_46', 'dvSave-2022_03_21_11_09_50',
'dvSave-2022_03_21_16_11_40', 'dvSave-2022_03_21_11_12_27',
'dvSave-2022_03_21_11_19_37', 'dvSave-2022_02_25_13_21_41',
'dvSave-2022_02_25_13_31_18', 'dvSave-2022_03_21_09_05_49'].
print("==>> pass it: ", foldName)
continue_

but there are sequences in _train.txt_ and _test.txt_ that load some of this data, and in training, the voxel file of the data sequences is needed, so should it be commented out in _event_to_voxel_coesot.py_?

**Comment by Alittlemole** [comment]
do not pass these files, then you can run the 'test.py' and evaluate it on matlab
