### ISSUE TITLE
train.txt val.txt

### ISSUE THREAD

**Issue by Alittlemole** [Event-AHU/COESOT#12]
if split is not None:
            if seq_ids is not None:
                raise ValueError('Cannot set both split_name and seq_ids.')
            if split == 'train':
                file_path = os.path.join(self.root, 'train.txt')
            elif split == 'val':
                file_path = os.path.join(self.root, 'val.txt')
            else:
                raise ValueError('Unknown split name')
            seq_ids = pandas.read_csv(file_path, header=None, dtype=np.int64).squeeze("columns").values.tolist()

    def _get_sequence_list(self):
        with open(os.path.join(self.root, 'list.txt')) as f:
            dir_list = list(csv.reader(f))
        dir_list = [dir_name[0] for dir_name in dir_list]
        return dir_list

There're no such files "train.txt"  "val.txt"  "list.txt"，where can i get them

**Comment by Tchuanm** [comment]
Hi, For this issue, you can check #2 which can help you to find the difference of train, val and test.txt.
