### ISSUE TITLE
How to use this code to test the FE108 dataset?

### ISSUE THREAD

**Issue by Wenjie-Wei** [Event-AHU/COESOT#13]
Hi, thanks for your work! This is my first time running the event-based tracking code. I have a simple question and hope to get your help.
I want to evaluate the FE108 dataset with this code. The current directory of the dataset is as shown below (only show the directory under /FE108/train/airplane/).
![1717244626233](https://github.com/Event-AHU/COESOT/assets/115059496/4a02d07a-aa6a-48b1-8985-8770cde37ce2)
If we run ' python tracking/test.py  ceutrack ceutrack_coesot --dataset fe108' directly, the following error will be displayed.
![1717244994264](https://github.com/Event-AHU/COESOT/assets/115059496/7afdb04e-1f07-4769-b2b8-d61145bfa648) 
Then, I run 'python /CEUTrack/scripts/event_to_voxel_FE108.py'. After run this command, each sequence will be processed into 3 folders: voxel, aps, dvs. But only the dvs folder has data (some *.png), the other two folders are empty. Finally, I still can't evaluate the FE108 dataset.

**Comment by Tchuanm** [comment]
Hi, Thanks for your attention. FE108 is truly a little hard  to process. I also meet some problems when I use it. 
This is the website of FE108 (https://zhangjiqing.com/dataset/), hope it can help you.
Beside, you need consider this line [https://github.com/Event-AHU/COESOT/blob/64e5e6f192d076bb53e8aced11f931c217ff37cc/CEUTrack/scripts/event_to_voxel_FE108.py#L115C8-L115C68](url), it saves the start and end frame of FE108, which will generate the corresponding frame into voxels and aps.
