### ISSUE TITLE
How  to Visualize the tracking?

### ISSUE THREAD

**Issue by i-am-the-light** [Event-AHU/COESOT#15]
Thanks a lot for your team's great contribution to Event-based tracking field! 
      But I wonder how can I visualize the results? In coesoet,  the author talked about show_CAM.py, but i can't figure out how to use it?
     `from .show_CAM import getCAM
      getCAM(response, curr_image, self.idx)`
Please give me a little tips, where can i get response, curr_image and self.idx?

**Comment by Tchuanm** [comment]
For  CEUTrack/scripts/show_CAM.py， there  are three parameters:
response is the response attention map of current frame.  
curr_image is the current RGB frame in one video,  [256,256,3]
idx is the index of current frame.  
This function is used for visualize each frame in one video and you can use it to check the tracking performance on each frame.
Actually, you can write your own visualize scripts (cover the feature on images ), and it's very easy to show.
