### ISSUE TITLE
some sequences have no event at all even if there are objects moving

### ISSUE THREAD

**Issue by RiverUp** [Event-AHU/COESOT#17]
in the following sequences in testing_subset folder, there seems something wrong with the attribute 'timestamp_start_of_frame', resulting in that event frames generated officially are white completely.
dvSave-2022_08_18_16_47_33
dvSave-2022_08_18_16_47_51
dvSave-2022_08_18_16_56_01
dvSave-2022_08_18_16_56_23
dvSave-2022_08_18_16_57_16

**Comment by wsasdsda** [comment]
@RiverUp Hello! Thanks for your attention! Firstly, we greatly appreciate your use of our dataset and identify this issue. In fact, we have to admit that the event stream of these video sequences has been damaged, resulting in the existence of all blank event frames. Therefore, this is equivalent to the event modality being in a state of modal missing.

**Comment by RiverUp** [comment]
I personally use the attribute 'timestamp_start_of_exposure' to replace and generate event frames. It seems work
