### ISSUE TITLE
 The Code "list.txt" in "lib.train.dataset.visevent.py".

### ISSUE THREAD

**Issue by SSSpc333** [Event-AHU/COESOT#2]
Thanks for your work. Since your dataset “COESOT” is not downloaded yet, I would like to run the code on "Visevent" first. 
In "lib.train.dataset.visevent.py", within the "_get_sequence_list()" function, there is an operation to open the "list.txt" file. I would like to know what content is associated with the Visevent dataset in "list.txt".

**Comment by wangxiao5791509** [comment]
Hi the COESOT can be downloaded now: https://github.com/Event-AHU/COESOT#dataset-download @SSSpc333

**Comment by SSSpc333** [comment]
Thank you very much. The COESOT is downloading.

**Comment by SSSpc333** [comment]
Hi, I have downloaded the COESOT. I encountered some issues while running the code. 
In "lib\train\dataset\coesot.py", "train.txt" and "val.txt" respectively are the training and testing sequences in COESOT. However, 
there is a reference to "list.txt" in the code of the "_get_sequence_list()" function, I want to know what contents are stored in    "list.txt". Really thanks for your help. 
@wangxiao5791509 @Tchuanm

**Comment by SSSpc333** [comment]
Thank you very much for your response. The above issue has been resolved, but there are still problems during the running. 
I'll give an example with a sequence. 
 The folder "dvSave-2021_09_01_06_59_10_voxel" will be obtained through "self._get_event_sequence_path(seq_id)" function. However, there is no "dvSave-2021_09_01_06_59_10_voxel" folder under the sequence "dvSave-2021_09_01_06_59_10".
Could you tell me how to get this "dvSave-2021_09_01_06_59_10_voxel" folder. @Tchuanm

**Comment by HusterYoung** [comment]
> Thank you very much for your response. The above issue has been resolved, but there are still problems during the running. I'll give an example with a sequence. The folder "dvSave-2021_09_01_06_59_10_voxel" will be obtained through "self._get_event_sequence_path(seq_id)" function. However, there is no "dvSave-2021_09_01_06_59_10_voxel" folder under the sequence "dvSave-2021_09_01_06_59_10". Could you tell me how to get this "dvSave-2021_09_01_06_59_10_voxel" folder. @Tchuanm

Hi～Is this voxel file necessary? Did you finally solve this problem?

**Comment by SSSpc333** [comment]
> > Thank you very much for your response. The above issue has been resolved, but there are still problems during the running. I'll give an example with a sequence. The folder "dvSave-2021_09_01_06_59_10_voxel" will be obtained through "self._get_event_sequence_path(seq_id)" function. However, there is no "dvSave-2021_09_01_06_59_10_voxel" folder under the sequence "dvSave-2021_09_01_06_59_10". Could you tell me how to get this "dvSave-2021_09_01_06_59_10_voxel" folder. @Tchuanm
> 
> Hi～Is this voxel file necessary? Did you finally solve this problem?

I have already solved this problem. If you need to run the baseline of COESOT, you will need to use voxel. The author has already provided the code for generating voxel.
