### ISSUE TITLE
The number of the test dataset

### ISSUE THREAD

**Issue by XDUSPONGE** [Event-AHU/COESOT#3]
As you say in the paper, the number of the testing subset is 527,  however, when I download the test dataset, I get the number of 528 (the number of the training is right 827), I guess if there is any mistake in the link of the baidu yun.

Best wishes

**Comment by XDUSPONGE** [comment]
And can you please send me the corresponding train.txt, test.txt and list.txt. I do not find it in the download file. Thanks

**Comment by Tchuanm** [comment]
[test.txt](https://github.com/Event-AHU/COESOT/files/11958284/test.txt)
[train.txt](https://github.com/Event-AHU/COESOT/files/11958288/train.txt)

The testing subset is 527 and the additional one video just ignore it.
