### ISSUE TITLE
About model weights

### ISSUE THREAD

**Issue by chenyucheng0221** [Event-AHU/COESOT#4]
There no link to download the model weights, could you kindly provide it?

**Comment by wangxiao5791509** [comment]
@chenyucheng0221  
The pre-traiend model is available at: https://github.com/Event-AHU/COESOT#ceutrack

**Comment by chenyucheng0221** [comment]
Thank you for your quick reply!

I hit another issue: when I run cmd: python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir ./output

Here comes this warning: WARNING: You are using tensorboardX instead sis you have a too old pytorch version.

The config file has been set but the corresponding folders are not created.

**Comment by chenyucheng0221** [comment]
Thank you for your quick reply!

Just double check, in this sentence: 
Download pre-trained [MAE ViT-Base weights](https://dl.fbaipublicfiles.com/mae/pretrain/mae_pretrain_vit_base.pth) and put it under $/pretrained_models

Download the model weights and put it on $/output/checkpoints/train/ceutrack

Is the MAE ViT-Base weights put under the folder pretrained_models and this one https://pan.baidu.com/s/1B6VPTqoltVCgOCfceK7bTA is put under folder /output/checkpoints/train/ceutrack?

Thanks

**Comment by Tchuanm** [comment]
u are right
