### ISSUE TITLE
The question about read train.txt

### ISSUE THREAD

**Issue by wangruilin12138** [Event-AHU/COESOT#6]
in CEUtrack/lib/train/dataset/ceosot.py  line32
`seq_ids = pandas.read_csv(file_path, header=None, dtype=np.int64).squeeze("columns").values.tolist()
`
During the reading process, the following issues may arise:
invalid literal for int() with base 10: 'dvSave-2021_09_01_06_59_10'

May I ask what the reasons are and how to solve them?

Thank you

**Comment by Tchuanm** [comment]
Hi, All files meet the same question or just this one video. ?

**Comment by wangruilin12138** [comment]
> Hi, All files meet the same question or just this one video. ?

 Thank you very much for your reply, all files meet the same question

**Comment by Tchuanm** [comment]
Sorry for late reply. I don't think all files will face this question.  dvSave-2021_09_01_06_59_10 is truely a file maybe error when read it by int64. 
Maybe you can reference #[5](https://github.com/Event-AHU/COESOT/issues/5#issuecomment-1697585377) to slove it.
