### ISSUE TITLE
toolkit results I plot is different with your figures in this repo readme?

### ISSUE THREAD

**Issue by laisimiao** [Event-AHU/COESOT#7]
I just downlaod you provided tracking results and plot SR, PR, NPR figures. But I find SR figure is same with yours. But PR and NPR values are different?
![image](https://github.com/Event-AHU/COESOT/assets/37405764/e5dac4f6-5b55-473b-8f05-1105484e564f)
![image](https://github.com/Event-AHU/COESOT/assets/37405764/ab597568-66aa-40db-b6a2-958b1b122222)

**Comment by Tchuanm** [comment]
Hi, I'm not sure where is the difference. I have run the [script](https://github.com/Event-AHU/COESOT/blob/main/COESOT_eval_toolkit/Evaluate_COESOT_benchmark_SP_RR_Only.m) again derectly to generate SR/PR. They are the same with the paper. Have you changed some thing?

**Comment by laisimiao** [comment]
you select the PR with plot Success when ranking_type    = 'AUC';
Bu that PR is not correct, you need to select PR when ranking_type    = 'threshold';

**Comment by laisimiao** [comment]
so solution is:
https://github.com/Event-AHU/COESOT/blob/aa610060cae50051d80476b5ed2fff81adea811f/COESOT_eval_toolkit/Evaluate_COESOT_benchmark_SP_RR_Only.m#L95-L98
to modify as following:
![image](https://github.com/Event-AHU/COESOT/assets/37405764/ee9ddb0b-d3f4-4aa3-90ec-4495f7882d91)

**Comment by laisimiao** [comment]
我已经加你微信了，因为你qq一直没回我XD
