### ISSUE TITLE
No matching checkpoint file found

### ISSUE THREAD

**Issue by Heyuting-Creator** [Event-AHU/COESOT#8]
Hello, I would like to ask some questions:
Checkpoints path: /COESOT-main/CEUTrack/output/checkpoints/train/ceutrack/CEUTrack_ep0049.pth.tar
Training:
export CUDA_VISIBLE_DEVICES=1
python tracking/train.py --script ceutrack --config ceutrack_coesot --save_dir . /output --mode single --nproc_per_node 1 --use_wandb 0
Display: No matching checkpoint file found.

My path is set correctly, but why does running it say chekpoints not found?

**Comment by Tchuanm** [comment]
You need to check and download the model from [here](https://github.com/Event-AHU/COESOT?tab=readme-ov-file#ceutrack).

**Comment by WHU-CC** [comment]
> 您好，我想问一些问题： 检查点路径：/COESOT-main/CEUTrack/output/checkpoints/train/ceutrack/CEUTrack_ep0049.pth.tar 训练：export CUDA_VISIBLE_DEVICES=1 python tracking/train.py --script ceutrack --config ceutrack_coesot --save_dir ./output --mode single --nproc_per_node 1 --use_wandb 0 显示：未找到匹配的 checkpoint 文件。
> 
> 我的路径设置正确，但为什么运行它时显示未找到 chekpoints？
请问你解决了吗

**Comment by Heyuting-Creator** [comment]
> > 您好，我想问一些问题： 检查点路径：/COESOT-main/CEUTrack/output/checkpoints/train/ceutrack/CEUTrack_ep0049.pth.tar 训练：export CUDA_VISIBLE_DEVICES=1 python tracking/train.py --script ceutrack --config ceutrack_coesot --save_dir ./output --mode single --nproc_per_node 1 --use_wandb 0 显示：未找到匹配的 checkpoint 文件。
> > 我的路径设置正确，但为什么运行它时显示未找到 chekpoints？
> > 请问你解决了吗

还是会显示未找到匹配的 checkpoint 文件，但是并不影响训练。

**Comment by Heyuting-Creator** [comment]
> > > > 您好，我想问一些问题： 检查点路径：/COESOT-main/CEUTrack/output/checkpoints/train/ceutrack/CEUTrack_ep0049.pth.tar 训练：export CUDA_VISIBLE_DEVICES=1 python tracking/train.py --script ceutrack --config ceutrack_coesot --save_dir ./output --mode single --nproc_per_node 1 --use_wandb 0 显示：未找到匹配的 checkpoint 文件。
> > > > 我的路径设置正确，但为什么运行它时显示未找到 chekpoints？
> > > > 请问你解决了吗
> > 
> > 
> > 还是会显示未找到匹配的 checkpoint 文件，但是并不影响训练。
> 
> 同学你好，请问您是怎么解决的呢？我也遇到了同样的问题，但是程序卡在了No matching checkpoint file found无法进行后面的训练

你的voxel文件是否生成？数据处理是否正确。
